name: correction

on:
    
    # push:

        
    #     branches: //When you have a push on the branch "dev" only
    #         - dev


    # push:
    #     branches: //When you have a push on any branch except "staging"
    #         - "!staging"

    push:
        branches: #When you have a push on any branch where the name starts with "feat"
            - "feat/**"

    # push:
    #     paths: //When only the files with a ts extension have been modified
    #         - "**.ts"


    # push:
    #     paths: #When a specific folder have been modified
    #         - "**.ts"




    workflow_dispatch: 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

    deploy:
        if: github.event_name != 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3